package me.coley.bmf.opcode;

import me.coley.bmf.opcode.impl.*;

public class OpcodeInst {
    // Other
    public static final NOP NOP = new NOP();
    public static final MONITORENTER MONITORENTER = new MONITORENTER();
    public static final MONITOREXIT MONITOREXIT = new MONITOREXIT();
    public static final IMPDEP1 IMPDEP1 = new IMPDEP1();
    public static final IMPDEP2 IMPDEP2 = new IMPDEP2();
    public static final BREAKPOINT BREAKPOINT = new BREAKPOINT();
    // Math
    public static final IADD IADD = new IADD();
    public static final DADD DADD = new DADD();
    public static final FADD FADD = new FADD();
    public static final LADD LADD = new LADD();
    public static final ISUB ISUB = new ISUB();
    public static final DSUB DSUB = new DSUB();
    public static final FSUB FSUB = new FSUB();
    public static final LSUB LSUB = new LSUB();
    public static final IMUL IMUL = new IMUL();
    public static final DMUL DMUL = new DMUL();
    public static final FMUL FMUL = new FMUL();
    public static final LMUL LMUL = new LMUL();
    public static final IDIV IDIV = new IDIV();
    public static final DDIV DDIV = new DDIV();
    public static final FDIV FDIV = new FDIV();
    public static final LDIV LDIV = new LDIV();
    public static final INEG INEG = new INEG();
    public static final DNEG DNEG = new DNEG();
    public static final FNEG FNEG = new FNEG();
    public static final LNEG LNEG = new LNEG();
    public static final IREM IREM = new IREM();
    public static final DREM DREM = new DREM();
    public static final FREM FREM = new FREM();
    public static final LREM LREM = new LREM();
    public static final ISHL ISHL = new ISHL();
    public static final LSHL LSHL = new LSHL();
    public static final ISHR ISHR = new ISHR();
    public static final LSHR LSHR = new LSHR();
    public static final IUSHR IUSHR = new IUSHR();
    public static final LUSHR LUSHR = new LUSHR();
    public static final IAND IAND = new IAND();
    public static final LAND LAND = new LAND();
    public static final IOR IOR = new IOR();
    public static final LOR LOR = new LOR();
    public static final IXOR IXOR = new IXOR();
    public static final LXOR LXOR = new LXOR();
    // Array
    public static final ARRAYLENGTH ARRAYLENGTH = new ARRAYLENGTH();
    public static final ATHROW ATHROW = new ATHROW();
    public static final IALOAD IALOAD = new IALOAD();
    public static final LALOAD LALOAD = new LALOAD();
    public static final FALOAD FALOAD = new FALOAD();
    public static final DALOAD DALOAD = new DALOAD();
    public static final AALOAD AALOAD = new AALOAD();
    public static final BALOAD BALOAD = new BALOAD();
    public static final CALOAD CALOAD = new CALOAD();
    public static final SALOAD SALOAD = new SALOAD();
    public static final IASTORE IASTORE = new IASTORE();
    public static final LASTORE LASTORE = new LASTORE();
    public static final FASTORE FASTORE = new FASTORE();
    public static final DASTORE DASTORE = new DASTORE();
    public static final AASTORE AASTORE = new AASTORE();
    public static final BASTORE BASTORE = new BASTORE();
    public static final CASTORE CASTORE = new CASTORE();
    public static final SASTORE SASTORE = new SASTORE();
    // Type-Conversion
    public static final I2L I2L = new I2L();
    public static final I2F I2F = new I2F();
    public static final I2D I2D = new I2D();
    public static final L2I L2I = new L2I();
    public static final L2F L2F = new L2F();
    public static final L2D L2D = new L2D();
    public static final F2I F2I = new F2I();
    public static final F2L F2L = new F2L();
    public static final F2D F2D = new F2D();
    public static final D2I D2I = new D2I();
    public static final D2L D2L = new D2L();
    public static final D2F D2F = new D2F();
    public static final I2B I2B = new I2B();
    public static final I2C I2C = new I2C();
    public static final I2S I2S = new I2S();
    // Stack
    public static final SWAP SWAP = new SWAP();
    public static final POP POP = new POP();
    public static final POP2 POP2 = new POP2();
    public static final DUP DUP = new DUP();
    public static final DUP2 DUP2 = new DUP2();
    public static final DUP_X1 DUP_X1 = new DUP_X1();
    public static final DUP_X2 DUP_X2 = new DUP_X2();
    public static final DUP2_X1 DUP2_X1 = new DUP2_X1();
    public static final DUP2_X2 DUP2_X2 = new DUP2_X2();
    // Stack - Compare
    public static final DCMPG DCMPG = new DCMPG();
    public static final DCMPL DCMPL = new DCMPL();
    public static final FCMPG FCMPG = new FCMPG();
    public static final FCMPL FCMPL = new FCMPL();
    public static final LCMP LCMP = new LCMP();
    // Const
    public static final ACONST_NULL ACONST_NULL = new ACONST_NULL();
    public static final ICONST ICONST_M1 = new ICONST(-1);
    public static final ICONST ICONST_0 = new ICONST(0);
    public static final ICONST ICONST_1 = new ICONST(1);
    public static final ICONST ICONST_2 = new ICONST(2);
    public static final ICONST ICONST_3 = new ICONST(3);
    public static final ICONST ICONST_4 = new ICONST(4);
    public static final ICONST ICONST_5 = new ICONST(5);
    public static final DCONST DCONST_0 = new DCONST(0);
    public static final DCONST DCONST_1 = new DCONST(1);
    public static final FCONST FCONST_0 = new FCONST(0);
    public static final FCONST FCONST_1 = new FCONST(1);
    public static final FCONST FCONST_2 = new FCONST(2);
    public static final LCONST LCONST_0 = new LCONST(0);
    public static final LCONST LCONST_1 = new LCONST(1);
    // Variable - Load
    public static final ALOAD ALOAD_0 = new ALOAD(0);
    public static final ALOAD ALOAD_1 = new ALOAD(1);
    public static final ALOAD ALOAD_2 = new ALOAD(2);
    public static final ALOAD ALOAD_3 = new ALOAD(3);
    public static final ILOAD ILOAD_0 = new ILOAD(0);
    public static final ILOAD ILOAD_1 = new ILOAD(1);
    public static final ILOAD ILOAD_2 = new ILOAD(2);
    public static final ILOAD ILOAD_3 = new ILOAD(3);
    public static final FLOAD FLOAD_0 = new FLOAD(0);
    public static final FLOAD FLOAD_1 = new FLOAD(1);
    public static final FLOAD FLOAD_2 = new FLOAD(2);
    public static final FLOAD FLOAD_3 = new FLOAD(3);
    public static final DLOAD DLOAD_0 = new DLOAD(0);
    public static final DLOAD DLOAD_1 = new DLOAD(1);
    public static final DLOAD DLOAD_2 = new DLOAD(2);
    public static final DLOAD DLOAD_3 = new DLOAD(3);
    public static final LLOAD LLOAD_0 = new LLOAD(0);
    public static final LLOAD LLOAD_1 = new LLOAD(1);
    public static final LLOAD LLOAD_2 = new LLOAD(2);
    public static final LLOAD LLOAD_3 = new LLOAD(3);
    // Variable - Store
    public static final ASTORE ASTORE_0 = new ASTORE(0);
    public static final ASTORE ASTORE_1 = new ASTORE(1);
    public static final ASTORE ASTORE_2 = new ASTORE(2);
    public static final ASTORE ASTORE_3 = new ASTORE(3);
    public static final ISTORE ISTORE_0 = new ISTORE(0);
    public static final ISTORE ISTORE_1 = new ISTORE(1);
    public static final ISTORE ISTORE_2 = new ISTORE(2);
    public static final ISTORE ISTORE_3 = new ISTORE(3);
    public static final FSTORE FSTORE_0 = new FSTORE(0);
    public static final FSTORE FSTORE_1 = new FSTORE(1);
    public static final FSTORE FSTORE_2 = new FSTORE(2);
    public static final FSTORE FSTORE_3 = new FSTORE(3);
    public static final DSTORE DSTORE_0 = new DSTORE(0);
    public static final DSTORE DSTORE_1 = new DSTORE(1);
    public static final DSTORE DSTORE_2 = new DSTORE(2);
    public static final DSTORE DSTORE_3 = new DSTORE(3);
    public static final LSTORE LSTORE_0 = new LSTORE(0);
    public static final LSTORE LSTORE_1 = new LSTORE(1);
    public static final LSTORE LSTORE_2 = new LSTORE(2);
    public static final LSTORE LSTORE_3 = new LSTORE(3);
    // Return
    public static final RETURN RETURN = new RETURN();
    public static final ARETURN ARETURN = new ARETURN();
    public static final IRETURN IRETURN = new IRETURN();
    public static final LRETURN LRETURN = new LRETURN();
    public static final FRETURN FRETURN = new FRETURN();
    public static final DRETURN DRETURN = new DRETURN();
}
